dist: trusty
sudo: required

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
      
script:
  - cd src && make
  - cd benchmarks && make && ./larson/larson 10 7 8 10000 1000 1 4 4
  - if [ $TRAVIS_OS_NAME == linux ]; then cd ../src && make && cd test && make && cd .. && export LD_PRELOAD=$PWD/libhoard.so && ../benchmarks/larson/larson 10 7 8 10000 1000 1 4 4 && ./test/mtest && unset LD_PRELOAD ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cd ../src && make ; fi

