dist: trusty
sudo: required

language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5.4" CC="gcc-5.4"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.4
    - g++-5.4
    - clang-3.9

general:
  build_dir: src
  branches:
    ignore:
      - gh-pages

machine:
  pre:
    - sudo apt-get -qq install clang-3.9
    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 60
  environment:
    CC: clang
    CXX: clang++

script:
  - cd src && make
  - cd ../benchmarks && make
  - if [ $TRAVIS_OS_NAME == linux ]; then cd ../src && make && cd test && make && cd .. && export LD_PRELOAD=$PWD/libhoard.so && ../benchmarks/larson/larson 10 7 8 10000 1000 1 4 4 && ./test/mtest && unset LD_PRELOAD ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cd ../src && make ; fi
